services:
  bot:
    build: .
    image: discord-bot:latest
    container_name: discord-bot
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7.4-alpine3.21
    container_name: redis-database
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1
    volumes:
      - redis-data:/data

volumes:
  redis-data:
